<?xml version="1.0" encoding="utf-8"?><Database Name="dryden_database" Class="googleMapDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=184.168.194.62;Initial Catalog=dryden_database;User ID=dryden" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="dryden_databaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.google_map" Member="google_maps">
    <Type Name="google_map">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="enabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="lat" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="lng" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
</Database>