#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dryden_database")]
public partial class newsDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertNew(New instance);
  partial void UpdateNew(New instance);
  partial void DeleteNew(New instance);
  #endregion
	
	public newsDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["dryden_databaseConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public newsDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public newsDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public newsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public newsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<New> News
	{
		get
		{
			return this.GetTable<New>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.News")]
public partial class New : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _date1;
	
	private string _date2;
	
	private string _date3;
	
	private string _date4;
	
	private string _title1;
	
	private string _title2;
	
	private string _title3;
	
	private string _title4;
	
	private string _text1;
	
	private string _text2;
	
	private string _text3;
	
	private string _text4;
	
	private string _image1;
	
	private string _image2;
	
	private string _image3;
	
	private string _image4;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void Ondate1Changing(string value);
    partial void Ondate1Changed();
    partial void Ondate2Changing(string value);
    partial void Ondate2Changed();
    partial void Ondate3Changing(string value);
    partial void Ondate3Changed();
    partial void Ondate4Changing(string value);
    partial void Ondate4Changed();
    partial void Ontitle1Changing(string value);
    partial void Ontitle1Changed();
    partial void Ontitle2Changing(string value);
    partial void Ontitle2Changed();
    partial void Ontitle3Changing(string value);
    partial void Ontitle3Changed();
    partial void Ontitle4Changing(string value);
    partial void Ontitle4Changed();
    partial void Ontext1Changing(string value);
    partial void Ontext1Changed();
    partial void Ontext2Changing(string value);
    partial void Ontext2Changed();
    partial void Ontext3Changing(string value);
    partial void Ontext3Changed();
    partial void Ontext4Changing(string value);
    partial void Ontext4Changed();
    partial void Onimage1Changing(string value);
    partial void Onimage1Changed();
    partial void Onimage2Changing(string value);
    partial void Onimage2Changed();
    partial void Onimage3Changing(string value);
    partial void Onimage3Changed();
    partial void Onimage4Changing(string value);
    partial void Onimage4Changed();
    #endregion
	
	public New()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date1", DbType="VarChar(50)")]
	public string date1
	{
		get
		{
			return this._date1;
		}
		set
		{
			if ((this._date1 != value))
			{
				this.Ondate1Changing(value);
				this.SendPropertyChanging();
				this._date1 = value;
				this.SendPropertyChanged("date1");
				this.Ondate1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date2", DbType="VarChar(50)")]
	public string date2
	{
		get
		{
			return this._date2;
		}
		set
		{
			if ((this._date2 != value))
			{
				this.Ondate2Changing(value);
				this.SendPropertyChanging();
				this._date2 = value;
				this.SendPropertyChanged("date2");
				this.Ondate2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date3", DbType="VarChar(50)")]
	public string date3
	{
		get
		{
			return this._date3;
		}
		set
		{
			if ((this._date3 != value))
			{
				this.Ondate3Changing(value);
				this.SendPropertyChanging();
				this._date3 = value;
				this.SendPropertyChanged("date3");
				this.Ondate3Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date4", DbType="VarChar(50)")]
	public string date4
	{
		get
		{
			return this._date4;
		}
		set
		{
			if ((this._date4 != value))
			{
				this.Ondate4Changing(value);
				this.SendPropertyChanging();
				this._date4 = value;
				this.SendPropertyChanged("date4");
				this.Ondate4Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title1", DbType="VarChar(50)")]
	public string title1
	{
		get
		{
			return this._title1;
		}
		set
		{
			if ((this._title1 != value))
			{
				this.Ontitle1Changing(value);
				this.SendPropertyChanging();
				this._title1 = value;
				this.SendPropertyChanged("title1");
				this.Ontitle1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title2", DbType="VarChar(50)")]
	public string title2
	{
		get
		{
			return this._title2;
		}
		set
		{
			if ((this._title2 != value))
			{
				this.Ontitle2Changing(value);
				this.SendPropertyChanging();
				this._title2 = value;
				this.SendPropertyChanged("title2");
				this.Ontitle2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title3", DbType="VarChar(50)")]
	public string title3
	{
		get
		{
			return this._title3;
		}
		set
		{
			if ((this._title3 != value))
			{
				this.Ontitle3Changing(value);
				this.SendPropertyChanging();
				this._title3 = value;
				this.SendPropertyChanged("title3");
				this.Ontitle3Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title4", DbType="VarChar(50)")]
	public string title4
	{
		get
		{
			return this._title4;
		}
		set
		{
			if ((this._title4 != value))
			{
				this.Ontitle4Changing(value);
				this.SendPropertyChanging();
				this._title4 = value;
				this.SendPropertyChanged("title4");
				this.Ontitle4Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_text1", DbType="VarChar(MAX)")]
	public string text1
	{
		get
		{
			return this._text1;
		}
		set
		{
			if ((this._text1 != value))
			{
				this.Ontext1Changing(value);
				this.SendPropertyChanging();
				this._text1 = value;
				this.SendPropertyChanged("text1");
				this.Ontext1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_text2", DbType="VarChar(MAX)")]
	public string text2
	{
		get
		{
			return this._text2;
		}
		set
		{
			if ((this._text2 != value))
			{
				this.Ontext2Changing(value);
				this.SendPropertyChanging();
				this._text2 = value;
				this.SendPropertyChanged("text2");
				this.Ontext2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_text3", DbType="VarChar(MAX)")]
	public string text3
	{
		get
		{
			return this._text3;
		}
		set
		{
			if ((this._text3 != value))
			{
				this.Ontext3Changing(value);
				this.SendPropertyChanging();
				this._text3 = value;
				this.SendPropertyChanged("text3");
				this.Ontext3Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_text4", DbType="VarChar(MAX)")]
	public string text4
	{
		get
		{
			return this._text4;
		}
		set
		{
			if ((this._text4 != value))
			{
				this.Ontext4Changing(value);
				this.SendPropertyChanging();
				this._text4 = value;
				this.SendPropertyChanged("text4");
				this.Ontext4Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image1", DbType="VarChar(MAX)")]
	public string image1
	{
		get
		{
			return this._image1;
		}
		set
		{
			if ((this._image1 != value))
			{
				this.Onimage1Changing(value);
				this.SendPropertyChanging();
				this._image1 = value;
				this.SendPropertyChanged("image1");
				this.Onimage1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image2", DbType="VarChar(MAX)")]
	public string image2
	{
		get
		{
			return this._image2;
		}
		set
		{
			if ((this._image2 != value))
			{
				this.Onimage2Changing(value);
				this.SendPropertyChanging();
				this._image2 = value;
				this.SendPropertyChanged("image2");
				this.Onimage2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image3", DbType="VarChar(MAX)")]
	public string image3
	{
		get
		{
			return this._image3;
		}
		set
		{
			if ((this._image3 != value))
			{
				this.Onimage3Changing(value);
				this.SendPropertyChanging();
				this._image3 = value;
				this.SendPropertyChanged("image3");
				this.Onimage3Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image4", DbType="VarChar(MAX)")]
	public string image4
	{
		get
		{
			return this._image4;
		}
		set
		{
			if ((this._image4 != value))
			{
				this.Onimage4Changing(value);
				this.SendPropertyChanging();
				this._image4 = value;
				this.SendPropertyChanged("image4");
				this.Onimage4Changed();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
